### ISSUE TITLE
Icon - but no temp in MATE panel after upgrade

### ISSUE THREAD

**Issue by bouxboux** [atareao/my-weather-indicator#72] opened 2020-07-20 18:51 UTC
MWI was working fine until I upgraded from Mint 19.3 to 20. The app is functional and the current conditions icon shows up in the panel, but have not been able to get temp (the number) to show up since. I have uninstalled/purged/removed files/directories manually - rebooted/reinstalled numerous times. Temp does not show up Cinnamon & KDE desktops either. MATE clock weather applet shows temp without problem. 

Sometimes when the app is open Preferences and Forecast, Evolution, Forcast Map, Moon Phase and Update Weather are grayed out, but not all the time. Can only make them work after a reboot. 

Any help is appreciated - I enjoy using this app.

**Comment by bouxboux** [comment] 2020-07-20 19:02
I saw you request another user to post the results of running /opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator in terminal. I had the grayed-out problem, so I closed MWI and ran the command - results follow:

<gettext.GNUTranslations object at 0x7f3d7f19be80>
#####################################################
System: Linux
Machine: x86_64
Node: mycomputer
Release: 5.4.0-42-generic
Version: #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020
Platform: Linux-5.4.0-42-generic-x86_64-with-glibc2.29
My-Weather-Indicator version: 0.9.4-0extras19.10.09
#####################################################

My-Weather-Indicator version: 0.9.4-0extras19.10.09
#####################################################

(my-weather-indicator:3939): Gtk-WARNING **: 14:57:42.813: Theme parsing error: colors.css:71:44: Invalid number for color value

(my-weather-indicator:3939): Gtk-WARNING **: 14:57:42.813: Theme parsing error: colors.css:72:44: Invalid number for color value

(my-weather-indicator:3939): Gtk-WARNING **: 14:57:42.813: Theme parsing error: colors.css:74:53: Invalid number for color value

(my-weather-indicator:3939): Gtk-WARNING **: 14:57:42.813: Theme parsing error: colors.css:75:53: Invalid number for color value

(my-weather-indicator:3939): Gtk-WARNING **: 14:57:42.813: Theme parsing error: colors.css:76:56: Invalid number for color value

(my-weather-indicator:3939): Gtk-WARNING **: 14:57:42.813: Theme parsing error: colors.css:77:65: Invalid number for color value
****** Requesting timezone identificacion
** OWM **
4221206 -82.8116031 32.9832812
1
***** refreshing weather *****
OK. Internet connection. HTTPConnection: www.google.com
--- Updating data in location 0 ---
****** Updating weather
****** Calculating rawOffset
-------------------------------------------------------
OpenWeatherMap Weather Service url:http://api.openweathermap.org/data/2.5/weather?id=4221206&appid=4516154e5c8a6494e7e13b550408c863
-------------------------------------------------------
****** Updated weather
None
Traceback (most recent call last):
  File "/opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator", line 36, in <module>
    main()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 953, in main
    mwi = MWI()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 124, in __init__
    self.load_preferences()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 349, in load_preferences
    self.update_weather()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 139, in update_weather
    self.update_menu(i)
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 804, in update_menu
    self.notifications[index].show()
gi.repository.GLib.Error: g-io-error-quark: Error calling StartServiceByName for org.freedesktop.Notifications: Timeout was reached (24)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_opt_extras.ubuntu.com_my-weather-indicator_bin_my-weather-indicator.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator", line 36, in <module>
    main()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 953, in main
    mwi = MWI()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 124, in __init__
    self.load_preferences()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 349, in load_preferences
    self.update_weather()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 139, in update_weather
    self.update_menu(i)
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 804, in update_menu
    self.notifications[index].show()
gi.repository.GLib.Error: g-io-error-quark: Error calling StartServiceByName for org.freedesktop.Notifications: Timeout was reached (24)

**Comment by bouxboux** [comment] 2020-07-20 19:38
After reboot, the app did not start. Tried to start manually from Menu. Showed a 'starting app' icon for a moment, then nothing. Went to Terminal and ran:

~ $ /opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator

<gettext.GNUTranslations object at 0x7f060ac12e80>
#####################################################
System: Linux
Machine: x86_64
Node: ss-Latitude-E6400
Release: 5.4.0-42-generic
Version: #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020
Platform: Linux-5.4.0-42-generic-x86_64-with-glibc2.29
My-Weather-Indicator version: 0.9.4-0extras19.10.09
#####################################################

My-Weather-Indicator version: 0.9.4-0extras19.10.09
#####################################################

(my-weather-indicator:3380): Gtk-WARNING **: 15:31:45.452: Theme parsing error: colors.css:71:44: Invalid number for color value

(my-weather-indicator:3380): Gtk-WARNING **: 15:31:45.452: Theme parsing error: colors.css:72:44: Invalid number for color value

(my-weather-indicator:3380): Gtk-WARNING **: 15:31:45.452: Theme parsing error: colors.css:74:53: Invalid number for color value

(my-weather-indicator:3380): Gtk-WARNING **: 15:31:45.452: Theme parsing error: colors.css:75:53: Invalid number for color value

(my-weather-indicator:3380): Gtk-WARNING **: 15:31:45.452: Theme parsing error: colors.css:76:56: Invalid number for color value

(my-weather-indicator:3380): Gtk-WARNING **: 15:31:45.452: Theme parsing error: colors.css:77:65: Invalid number for color value
application already running

Does not show up in MATE System Monitor as running. No icon in Panel.

**Comment by bouxboux** [comment] 2020-10-22 20:33
Just an FYI - I still have no temp numbers in my MATE panel.

**Comment by fejjj** [comment] 2022-01-23 23:30
I have the same issue

**Comment by atareao** [comment] 2023-04-21 04:17
Duplicate of #97

**Closed by atareao** 2023-04-21 04:17 UTC
