### ISSUE TITLE
No "Blustery" Icon

### ISSUE THREAD

**Issue by cement-head** [atareao/my-weather-indicator#28] opened 2017-01-26 12:38 UTC
Need a Blustery icon.

**Comment by Spurlos** [comment] 2017-07-04 11:11
Duplicate of https://github.com/atareao/my-weather-indicator/issues/15 issue

**Comment by csola48** [comment] 2017-08-12 09:51
There is no "Blustery" icon yet! ... :(

**Comment by 1dragosh** [comment] 2017-11-07 12:03
This has been fixed [https://github.com/atareao/my-weather-indicator/issues/15#issuecomment-342414816]here.

**Comment by cement-head** [comment] 2017-11-07 15:20
The new build won't connect to weather services (Yahoo, or OpenWeather) - it says "No internet connection"

**Closed** 2017-11-07 20:01 UTC
